---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 5

    steps:
      - uses: sbrunner/test-mask-action@master

      - name: test mask
        run: echo 086abcdef010

      - run: "false"
